#!/usr/bin/bash
gum confirm "$(gum style --border normal --margin '1' --padding '1 2' --border-foreground 212 'Welcome to jade-tui, ready to start your installation?')" && CONTINUE=true
if [[ $CONTINUE != "true" ]]; then
	echo "Exiting. Have a good day!"
	exit
fi

keymap=$(localectl list-keymaps | gum filter --placeholder "select a keymap")
echo "keymap: $keymap"

timezone=$(timedatectl list-timezones | gum filter --placeholder "select a timezone")
echo "timezone: $timezone"

clear
gum style --border normal --margin "1" --padding "1 2" --border-foreground 212 "Please enter your username"
username=$(gum input --placeholder "Please enter your username")
echo "username: $username"
matches="false"
passwrong="false"
while [[ "$matches" == "false" ]]; do
	clear
	if [[ "$passwrong" == "true" ]]; then
		gum style --border normal --margin "1" --padding "1 2" --border-foreground 212 "Passwords did not match, please type the password again"
	else
		gum style --border normal --margin "1" --padding "1 2" --border-foreground 212 "Now enter your password"
	fi
	password=$(gum input --password --placeholder "Please enter a password")
	echo "password: $password"
	gum style --border normal --margin "1" --padding "1 2" --border-foreground 212 "Verify your password"
	password_verif=$(gum input --password --placeholder "Type your password again")
	if [[ "$password" == "$password_verif" ]]; then
		matches="true"
	else
		passwrong="true"
	fi
done
password=openssl passwd -crypt ${password}

different_root_password=true
gum confirm "$(gum style --border normal --margin '1' --padding '1 2' --border-foreground 212 'Use same password for root?')" && different_root_password=false
if [[ $different_root_password != "true" ]]; then
	echo "same password as user"
	root_password=${password}
else
	root_matches="false"
	root_passwrong="false"
	while [[ "$root_matches" == "false" ]]; do
		clear
		if [[ "$root_passwrong" == "true" ]]; then
			gum style --border normal --margin "1" --padding "1 2" --border-foreground 212 "Passwords did not match, please type the root password again"
		else
			gum style --border normal --margin "1" --padding "1 2" --border-foreground 212 "Now enter your root password"
		fi
		root_password=$(gum input --password --placeholder "Please enter a root password")
		echo "root password: $root_password"
		gum style --border normal --margin "1" --padding "1 2" --border-foreground 212 "Verify your root password"
		root_password_verif=$(gum input --password --placeholder "Type your root password again")
		if [[ "$root_password" == "$root_password_verif" ]]; then
			root_matches="true"
		else
			root_passwrong="true"
		fi
	done
fi
root_password=openssl passwd -crypt ${root_password}

clear
gum style --border normal --margin "1" --padding "1 2" --border-foreground 212 "Please enter a hostname"
hostname=$(gum input --placeholder "Please enter a hostname")

clear
gum style --border normal --margin "1" --padding "1 2" --border-foreground 212 "Please select the disk to install to  $(gum style --foreground 212 'WARNING: This will erease the whole disk')"
disk=$(lsblk -pdo name | grep -v zram | grep -v NAME | grep -v loop | grep -v sr | gum choose --limit 1)
echo "disk: ${disk}"
disk=$(echo ${disk} | awk '{ print substr ($0, 6 ) }')

clear
gum style --border normal --margin "1" --padding "1 2" --border-foreground 212 "Select a desktop to use"
desktop=$(gum choose --limit 1 gnome kde budgie mate cinnamon lxqt sway i3gaps herbstluftwm awesome bspwm)
echo "desktop: ${desktop}"

clear
gum style --border normal --margin "1" --padding "1 2" --border-foreground 212 "Some miscellaneous settings" "Use space to enable/disable"
misc_settings=$(gum choose --limit 2 "Enable ipv6" "Enable timeshift")
enable_ipv6="false"
enable_timeshift="true"
if [[ $misc_settings == *"ipv6"* ]]; then
	enable_ipv6="true"
fi
if [[ $misc_settings == *"timeshift"* ]]; then
	enable_timeshift="true"
fi
echo "ipv6: ${enable_ipv6}"
echo "timeshift: ${enable_timeshift}"

bios_type=$([ -d /sys/firmware/efi ] && echo UEFI || echo Legacy BIOS)
echo "bios type: ${bios_type}"

clear
CONTINUE=false
gum confirm "$(gum style --border normal --margin '1' --padding '1 2' --border-foreground 212 "Summary, is this correct?" "" "keymap: ${keymap}" "timezone: ${timezone}" "username: ${username}" "password: ${password}" "root-password: ${root_password}" "hostname: ${hostname}" "disk: ${disk}" "desktop: ${desktop}" "ipv6: ${enable_ipv6}" "timeshift: ${enable_timeshift}")" && CONTINUE=true
if [[ $CONTINUE != "true" ]]; then
	echo "Exiting. Have a good day!"
	exit
else
	echo "{
		\"partition\": {
			\"device\": \"${disk}\",
			\"mode\": \"Auto\",
			\"efi\": true,
			\"partitions\": []
		},
		\"bootloader\": {
			\"type\": \"grub-efi\",
			\"location\": \"/boot/efi\"
		},
		\"locale\": {
			\"locale\": [
				\"en_US.UTF-8 UTF-8\"
			],
			\"keymap\": \"${keymap}\",
			\"timezone\": \"${timezone}\"
		},
		\"networking\": {
			\"hostname\": \"${hostname}\",
			\"ipv6\": ${enable_ipv6}
		},
		\"users\": [
			{
				\"name\": \"${username}\",
				\"password\": \"${password}\",
				\"hasroot\": true,
				\"shell\": \"zsh\"
			}
		],
		\"rootpass\": \"${root_password}\",
		\"desktop\": \"${desktop}\",
		\"timeshift\": ${enable_timeshift},
		\"extra_packages\": [],
		\"flatpak\": true,
		\"zramd\": true,
		\"unakite\": {
			\"enable\": false,
			\"root\": \"/dev/null\",
			\"oldroot\": \"${disk}\",
			\"efidir\": \"/dev/null\",
			\"bootdev\": \"/dev/null\"
		},
		\"kernel\": \"linux\"
	}" > config.json
fi

CONTINUE=false
gum confirm "$(gum style --border normal --margin '1' --padding '1 2' --border-foreground 212 "Are you sure you want to install?" "$(gum style --foreground 212 'WARNING: This will erease the whole disk')")" && CONTINUE=true
if [[ $CONTINUE != "true" ]]; then
	echo "Exiting. Have a good day!"
	exit
else
	sudo jade config config.json
fi